kind: ArgoCD
apiVersion: argoproj.io/v1alpha1
metadata:
  name: argocd
  namespace: openshift-operators
spec:
  resourceTrackingMethod: annotation+label
  controller:
    resources:
      limits:
        cpu: 2000m
        memory: 2048Mi
      requests:
        cpu: 250m
        memory: 1024Mi
  ha:
    enabled: false
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 250m
        memory: 128Mi
  rbac:
    defaultPolicy: ''
    policy: |-
      g, system:cluster-admins, role:admin
      p, role:admin-sno-4, applications, *, project-sno-4/*, allow
      p, role:admin-sno-4, clusters, get, project-sno-4/*, allow
      p, role:admin-sno-4, repositories, *, project-sno-4/*, allow
      g, admin-sno-4, role:admin-sno-4
      p, role:admin-sno-5, applications, *, project-sno-5/*, allow
      p, role:admin-sno-5, clusters, get, project-sno-5/*, allow
      p, role:admin-sno-5, repositories, *, project-sno-5/*, allow
      g, admin-sno-5, role:admin-sno-5
      p, role:admin-sno-6, applications, *, project-sno-6/*, allow
      p, role:admin-sno-6, clusters, get, project-sno-6/*, allow
      p, role:admin-sno-6, repositories, *, project-sno-6/*, allow
      g, admin-sno-6, role:admin-sno-6
      p, role:admin-sno-7, applications, *, project-sno-7/*, allow
      p, role:admin-sno-7, clusters, get, project-sno-7/*, allow
      p, role:admin-sno-7, repositories, *, project-sno-7/*, allow
      g, admin-sno-7, role:admin-sno-7
    scopes: '[groups]'
  redis:
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 250m
        memory: 128Mi
  repo:
    resources:
      limits:
        cpu: 1000m
        memory: 1024Mi
      requests:
        cpu: 250m
        memory: 256Mi
  resourceExclusions: "- apiGroups:\n  - tekton.dev\n  clusters:\n  - '*'\n  kinds:\n  - TaskRun\n  - PipelineRun        \n"
  server:
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 125m
        memory: 128Mi
    route:
      enabled: true
  sso:
    dex:
      openShiftOAuth: true
      resources:
        limits:
          cpu: 500m
          memory: 256Mi
        requests:
          cpu: 250m
          memory: 128Mi
    provider: dex
